server:
  port: 8765

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  cloud:
    gateway:
      routes:
        - id: currency-exchange-service
          uri: lb://currency-exchange-service
          predicates:
            - Path=/currency/**
        - id: currency-conversion-service
          uri: lb://currency-conversion-service
          predicates:
            - Path=/conversion/**

  sleuth:
    sampler:
      probability: 1.0

  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus, metrics
#
#
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'